### ISSUE TITLE
Cross-site links not working

### ISSUE THREAD

**Issue by The-Kergan** [PREVAC/www.coronavirus-toolkit.com#143]
**Describe the bug**
Many of the links between various pages on the site appear to be coded correctly, but do not work.

**To Reproduce**
1. Go to https://www.coronavirus-toolkit.com/f1-preparing-for-coronavirus-lock-down.html#t4-household-lockdown
2. Click on 'T1-Coronavirus Symptom Tracker' beneath 'What You Need'

**Expected behavior**
Should jump to Tool 1

**Comment by bnorikane** [comment]
That link in 2. is spelled wrong. It should have hypens not underscores.
"https://www.coronavirus-toolkit.com/f1-preparing-for-coronavirus-lock-down.html#t1_coronavirus_symptom_tracker" 
I will fix it. 
Do you know of others offhand?
Otherwise, I will check manually.

**Comment by bnorikane** [comment]
I have not found any more crosslinks that do not work.
