### ISSUE TITLE
Can’t upload any file to Github

### ISSUE THREAD

**Issue by The-Kergan** [PREVAC/www.coronavirus-toolkit.com#153]
**Describe the bug**
Neither @bnorikane nor @The-Kergan can uploade images or pdf files to GitHub.

**To Reproduce**
I sent a video a while back. Symptoms have not changed and Git tech support have stopped trying to help.

**Expected behavior**
Files upload easily.

**Possible Resolution**

1. [lowering Shields in the panel on GitHub should resolve this](https://community.brave.com/t/cant-upload-any-file-to-github/40200)

**Comment by zuedev** [comment]
@The-Kergan "Shields" is a feature of Brave, the browser. It has nothing to do with GitHub.

**Comment by The-Kergan** [comment]
Ah, thanks. Git-fork worked, however.

**Comment by bnorikane** [comment]
Can we close this issue?
We cannot use GitHub Upload feature to move files to docs/.vuepress/public. 
The workaround is to use a Git repo on your local computer, add the files to a local branch, then push the branch to GitHub.

**Comment by zuedev** [comment]
Issue with GitHub has been sent, awaiting response. Will update on Slack if anything changes.
